ShopAdoAspNet/ShopAdoAspNet/Controllers/GoodController.cs
using AutoMapper;
using ShopAdo.BLL.DTO;
using ShopAdo.BLL.Services;
using ShopAdoAspNet.Models;
using ShopAdoAspNet.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopAdoAspNet.Controllers
{
    [Authorize]
    public class GoodController : Controller
    { 
        private readonly IService<GoodDTO> _goodService;
        private readonly IService<CategoryDTO> _categoryService;
        private readonly IService<ManufacturerDTO> _manufacturerService;
        private readonly IService<PhotoDTO> _photoService;
        private readonly IMapper _mapper;

        public GoodController(IService<GoodDTO> goodService, IService<CategoryDTO> categoryService, IService<ManufacturerDTO> manufacturerService, IService<PhotoDTO> photoService)
        {
            _goodService = goodService;
            _categoryService = categoryService;
            _manufacturerService = manufacturerService;
            _photoService = photoService;

            var configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<GoodDTO, CreateGoodViewModel>()
                        .ForMember("Photos", opt => opt.MapFrom(good => _photoService.GetAll().Where(x => x.GoodId == good.GoodId).ToList()))
                        .ForMember("Manufacturers", opt => opt.MapFrom(good => new SelectList(_manufacturerService.GetAll(), "ManufacturerId", "ManufacturerName")))
                        .ForMember("Categories", opt => opt.MapFrom(good => new SelectList(_categoryService.GetAll(), "CategoryId", "CategoryName")));
                cfg.CreateMap<CreateGoodViewModel, GoodDTO>();
            });
            _mapper = configuration.CreateMapper();
        }

        public ActionResult Index()
        {
            return View(_goodService.GetAll());
        }

        public ActionResult Details(int id)
        {
            return View(_goodService.Get(id));
        }

        public ActionResult Delete(int id)
        {
            _goodService.Delete(_goodService.Get(id));
            return RedirectToAction("Index", "Good");
        }

        public ActionResult Edit(int id)
        {
            var good = _goodService.Get(id);
            var viewModel = _mapper.Map<CreateGoodViewModel>(good);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(CreateGoodViewModel viewModel, IEnumerable<HttpPostedFileBase> fileUpload)
        {
            var good = _mapper.Map<GoodDTO>(viewModel);

            foreach (var photo in fileUpload)
            {
                if (photo == null)
                    break;

                string path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Uploaded/");
                string filename = Path.GetFileName(photo.FileName);
                string pathToFile = Path.Combine(path, filename);
                if (filename != null)
                    photo.SaveAs(pathToFile);

                _photoService.AddOrUpdate(new PhotoDTO { GoodId = good.GoodId, PhotoPath = pathToFile });
            }

            _goodService.AddOrUpdate(good);
            return RedirectToAction("Index", "Good");
        }

        public ActionResult Add()
        {
            var viewModel = _mapper.Map<CreateGoodViewModel>(new GoodDTO());

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(CreateGoodViewModel viewModel, IEnumerable<HttpPostedFileBase> fileUpload)
        {
            var good = _mapper.Map<GoodDTO>(viewModel);

            foreach (var photo in fileUpload)
            {
                if (photo == null)
                    break;

                string path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Uploaded/");
                string filename = Path.GetFileName(photo.FileName);
                string pathToFile = Path.Combine(path, filename);
                if (filename != null)
                    photo.SaveAs(pathToFile);

                _photoService.AddOrUpdate(new PhotoDTO { GoodId = good.GoodId, PhotoPath = pathToFile });
            }

            _goodService.AddOrUpdate(good);
            return RedirectToAction("Index", "Good");
        }
    }
}

ShopAdoAspNet/ShopAdoAspNet/Controllers/PhotoController.cs
using ShopAdo.BLL.DTO;
using ShopAdo.BLL.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopAdoAspNet.Controllers
{
    [Authorize]
    public class PhotoController : Controller
    {
        private readonly IService<PhotoDTO> _photoService;

        public PhotoController(IService<PhotoDTO> photoService)
        {
            _photoService = photoService;
        }

        public ActionResult Delete(int id)
        {
            var photo = _photoService.Get(id);
            if (System.IO.File.Exists(photo.PhotoPath))
                System.IO.File.Delete(photo.PhotoPath);

            _photoService.Delete(photo);
            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

ShopAdoAspNet/ShopAdoAspNet/Views/Good/Add.cshtml
@model ShopAdoAspNet.ViewModels.CreateGoodViewModel

@{
    ViewBag.Title = "Add Good";
}

<main class="container mt-5">
    <div class="row">
        @using (Html.BeginForm("Add", "Good", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.GoodName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GoodName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GoodName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GoodCount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GoodCount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GoodCount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CategoryId, Model.Categories, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ManufacturerId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.ManufacturerId, Model.Manufacturers, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ManufacturerId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <input type="file" name="fileUpload" multiple />
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
        }
    </div>
</main>

ShopAdoAspNet/ShopAdoAspNet/Views/Good/Details.cshtml
@model ShopAdo.BLL.DTO.GoodDTO

@{
    ViewBag.Title = "Good Details";
}

<main class="container mt-3">
    <div class="row">
        <table class="table">
            <thead>
                <td>Good Id</td>
                <td>Good</td>
                <td>Category</td>
                <td>Manufacturer</td>
                <td>Price</td>
                <td>Count</td>
            </thead>
            <tbody>
                <tr>
                    <td>@Model.GoodId</td>
                    <td>@Model.GoodName</td>
                    <td>@Model.CategoryName</td>
                    <td>@Model.ManufacturerName</td>
                    <td>@Model.Price</td>
                    <td>@Model.GoodCount</td>
                </tr>
            </tbody>
        </table>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.GoodId }, new { @class = "text-success" }) |
        @Html.ActionLink("Back to List", "Index", "Good", new { @class = "text-success" })
    </p>
</main>

ShopAdoAspNet/ShopAdoAspNet/Views/Good/Edit.cshtml
@model ShopAdoAspNet.ViewModels.CreateGoodViewModel

@{
    ViewBag.Title = "Good Edit";
}

<main class="container mt-5">
    <div class="row">
        @using (Html.BeginForm("Edit", "Good", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.GoodId)

                <div class="form-group">
                    @Html.LabelFor(model => model.GoodName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GoodName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GoodName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.GoodCount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GoodCount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GoodCount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.CategoryId, Model.Categories, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ManufacturerId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.ManufacturerId, Model.Manufacturers, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ManufacturerId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <input type="file" name="fileUpload" multiple />
                    </div>
                </div>

                <table class="table mt-5 mb-5">
                    <thead>
                        <td>Photo URI</td>
                    </thead>
                    <tbody>
                        @foreach (var photo in Model.Photos)
                        {
                            <tr>
                                <td>@photo.PhotoPath</td>
                                <td>@Html.ActionLink("Delete", "Delete", "Photo", new { id = photo.PhotoId }, new { @class = "text-danger" })</td>
                            </tr>
                        }
                    </tbody>
                </table>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</main>

ShopAdoAspNet/ShopAdoAspNet/Views/Good/Index.cshtml
@model IEnumerable<ShopAdo.BLL.DTO.GoodDTO>

@{
    ViewBag.Title = "Good Table";
}

<main class="container">
    <div class="row mt-3">
        @Html.ActionLink("Create new", "Add", null, new { @class = "btn btn-success" })
    </div>
    <div class="row mt-3">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.GoodId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GoodName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ManufacturerName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CategoryName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GoodCount)
                </th>
                <th></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.GoodId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GoodName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ManufacturerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CategoryName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GoodCount)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.GoodId }, new { @class = "text-warning" }) |
                        @Html.ActionLink("Details", "Details", new { id = item.GoodId }, new { @class = "text-success" }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.GoodId }, new { @class = "text-danger" })
                    </td>
                </tr>
            }
        </table>
    </div>
</main>